version: '3'
services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: jekyll serve --no-watch --force_polling --source src
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729